/* eslint max-len: 0 */

import React from 'react';

export default () => (
  <div>
    <img className="narrator-pic" src="profilepics/lisa.jpg" alt="" />
    <h4 className="story-title"><em>Lisa, Freelancer</em></h4>
    <p><em>This week we got a chance to interview Lisa Bronwyn. Lisa is a Freelance Software Developer. She’s getting quite knowledgeable in PHP and JavaScript and has worked in WordPress for almost a decade. Here is the interview:</em></p>
    <p><strong>Can you tell us a little bit about your background?</strong></p>
    <p>“I grew up in L.A., and was born into fashion and the entertainment industry. If you watched TV and movies during 2007-2008, you probably saw me and didn’t realize it. I’ve already had several careers, but it’s easier than you think to become very good at something you eventually dislike. I think I stuck around longer because of some good people and the life lessons I needed to learn."</p>
    <p><strong>What inspired you to become a software engineer?</strong></p>
    <p>“Reinvention, and the fact I’ve been using computers since the 7th grade (Apple IIe Plus). Since then, I’ve been fascinated with how things work (or don’t work) with both hardware and software. Also, I was on BBS during the earlier days of the internet, looking for people to play D&D with! You can relate to the first time you ever used the internet, right? Magical, wondrous and limitless, both in good and bad ways. Speaking of those careers from before, I was a makeup artist and became an esthetician at one point. I remember it vividly: the salon and spa software we were using was complete sh*t! I mean no offense to anyone, but it was the best available and was the most expensive too. Yet, we had to settle for it. My former boss watched me go through bug after bug. As I vented to her, she said that I’d be better at fixing software than being an esthetician! ‘Make your own software, it'll be good,’ she said. I wish I would have heeded her wisdom sooner.”</p>
    <p><strong>What are some challenges you face along this journey?</strong></p>
    <p>“Getting in my own way; and sexism, ageism, racism. I’ve been thinking about this a lot lately, that you can benefit from white privilege even if you identify as Latinx, etc., if you’re perceived to be white. My mom’s side is Spanish-Mexican-Native American and you’d be amazed at what I’ve heard people in tech say about people of color! Hey, I’m not your buddy if you’re trying to spread ignorance and hate. Their faces when they try and backpedal, it’s gross. It’s up to everyone to call it out and squash it as it happens, otherwise, we’re no better than the -ist themselves. Ageism is also real and you might as well have one foot in the grave if you dare to live past 30, lol. Real talk here: I have two little kids and find it perplexing that many companies in Silicon Valley view having a family as a sign of weakness! My ex (also in tech) was told verbatim that ‘family is an extracurricular activity.’”</p>
    <p><strong>How do you overcome these challenges?</strong></p>
    <p>“It’s hard to believe in anything when you can’t believe in yourself at times. I’ve done my best to slay the concept of scarcity, you know, that there’s not enough to go around. You don't have to compete with other people, musical chairs style. Be the best version of yourself and strive not to repeat the same lessons if you don’t have to. At the end of the day, my conscience lets me rest my head on my pillow at night; I’m ok with myself. I also have a mantra lately: I haven’t come this far to only come this far. So I strive to be better every day; we don’t know everything, but we can ask better questions, right? My innate curiosity and love of learning have taken me this far and I can’t wait to see what happens next."</p>
    <p><strong>How did you balance learning to program and caring for your kids?</strong></p>
    <p>"Oh, you mean the daily challenge?! Parents and caregivers. The struggle is real. It’s exhausting to even type this! For me, I know that my peak mental times are later in the day. I do my best work in the wee hours of the night and I’ve been this way since grade school. After the kids are in bed is when I can sit down at the computer with intense focus. One good thing about parenthood is that there are a lot of things that are pretty clear. Hear me out, I’m talking about logistics like scheduling and planning ahead, from calendars to using time management and note apps on your phone. There are 24 hours in the day and you can delegate them in advance, much of the time. So I do that whenever possible."</p>
    <p><strong>What are your thoughts on Learners Guild?</strong></p>
    <p>"Although I didn’t get what I needed out of the program, I made some lifelong friendships! One thing I'll shout from the rooftops is that Learners Guild is not the program for you if you have any issues with focus, especially ADHD. It’s very hard to ‘know what you don’t know’, so to speak, if there’s no curriculum (which was much of my experience with the program). It sucks if you're going along with it because you don't know any better! I’m grateful that I was able to take chances with studies in functional programming and become familiar with working in teams. Oh, and Git! Git patch, stash, and pop are your good friends. I also regained some much-needed self-esteem, as it’s not easy to transition from being a mostly stay-at-home mom with my youngest to becoming a software engineer."</p>
    <p><strong>If you could go back in time, what would you do differently in regards to becoming a software engineer?</strong></p>
    <p>"I’d have read all that I could about imposter syndrome. I’d have been a better listener and took better inventory of what I wasn’t learning. I'd also listen to my BS meter and not ignore it when it goes off."</p>
    <p><strong>What are some roadblocks/pitfalls that people who are starting programming could avoid?</strong></p>
    <p>"You don't have to lose your money or your mind when learning to program. With the abundant free and low-cost resources available on the internet, you can avoid a lot of hassle and not waste time and money by participating in some of the formal programs out there. You don't have to reinvent the wheel. When that BS meter I mentioned from before goes off, you must not ignore it! Your instincts are better than you think, so heed them."</p>
    <p><strong>What are some last thoughts/advice?</strong></p>
    <p>"On your self-taught coding journey, find someone with your learning style. This could be a mentor, coffee buddy, friend that you trust, friend of a friend that you trust but it should be someone specifically with your learning style, or close to it. It's like playing tennis with players that are more advanced, you’ll get better just by playing with them. Side hustle, side hustle. Keep a level head by being realistic in that it can take a long time to get hired as a developer. Have multiple streams of opportunity. Keep your Github fresh. Another thing I’ve seen is that it can take nearly two months to get onboarded. And this is after multiple on-site interviews before being hired. Oh, and rather than focusing on a specific programming language or hot new framework, work with data structures and algorithms! It's like a house, you can't put windows and walls where there is no foundation. There are so many good courses on Udemy, Coursera, Khan Academy, etc. I'm not proud of this but I bypassed the math prerequisites for two Computer Science classes in college. Don't be me. That bit me in the butt, hard. I got a B+ in Objective-C but we won't talk about the other class. I suffered so that you don't have to. Yet I still struggle with math concepts. I seemingly imagine that these are easier for people that made it through the math that I avoided as a Psychology major. I tell my older kid this: "It's not that you don't like math, it's that you don't like the way that it's been taught. I'm the same way, so do a lot of work over and over until you get it. Speak up and ask questions when you don't!” Math is a door to different worlds and you can't get through the doors if they're automatically closed because you didn’t take some classes. Those doors are much harder to open later."</p>
    <p><em>For more awesome stories check out our <a href="https://www.facebook.com/buzzybee.io/" target="_blank" rel="noopener noreferrer">facebook</a> and <a href="https://medium.com/@buzzybeeio" target="_blank" rel="noopener noreferrer">medium</a> page!</em></p>
  </div>
);
