/* eslint max-len: 0 */

import React from 'react';

const Story = () => (
  <div>
    <img className="narrator-pic" src="profilepics/richard.jpg" alt="" />
    <h4 className="story-title"><em>Richard, Web Developer at Ascendify</em></h4>
    <p><em>This week we got a chance to interview Richard Chan. He is a Web Developer at Ascendify. Richard is passionate about helping people and wants to eventually create software to help Venezuela, the country that he grew up in. Here is the interview:</em></p>
    <p><strong>Can you tell us a little bit about your background?</strong></p>
    <p>"I was born in the Bay Area then I moved to Venezuela for 18 years. So I grew up there and Spanish was my first language. After highschool, I moved back to the Bay Area just for college because the opportunities here are better after you get a bachelor’s degree. I went to City College of San Francisco for my associate’s degree and transferred to San Francisco State University because there was a transfer program at University of Hong Kong that I wanted to go to. I went Hong Kong for the first time in 2009 and thought, 'Wow, this is a pretty amazing place!' along with the energy, vibe, and the public transportation. I realized I wanted to live there for a year and when I came back from the trip and I met with a SFSU student who went to exchange there for a year so I wanted to transfer there and just get into that program. Fortunately, I was able to get into the program with some scholarships. And that was the best year of my college life. During college I studied business, which is something that is not related to software development or web development, mainly because I wanted to be a business guy and open my own company but I realized I needed more hard skills, like design or software. Or you know, something more hands-on than just having this big idea and just finding two to three people that I trust to build something."</p>
    <p><strong>So was this your starting point to going into SE or WD?</strong></p>
    <p>"I was actually already building websites. The first time I touched HTML/CSS was back in high school. We had a programming class and I was just changing stuff with HTML and CSS and thought it was pretty fun. But I never got into it until I graduated. And then I thought about what is it that I wanted to do in 15- 20 years that I wouldn’t regret."</p>
    <p><strong>So you see yourself, 15 - 20 years from now, working as a web developer?</strong></p>
    <p>"Yeah, I think the future is leaning towards software and technology so my main goal is to go back to my country and help build software or something useful for the people in Venezuela once the country gets better. I see that as a long term goal, something for the next 15 - 20 years. So right now I'm trying to get the most out of the Bay Area since it’s the place to be for technology and innovation. I’m learning a lot from my current job."</p>
    <p><strong>Where do you currently work at?</strong></p>
    <p>"I work at Ascendify, it’s a talent management and acquisition company. We do HR related stuff. From end-to- end. When you look for a job you go to a website, see all the job list, click on the job you like, see all the different responsibilities/description; we have the backend data and that app is pretty complex. It’s a talent management spec. It helps for onboarding - to develop and help you get engaged with the company to grow."</p>
    <p><strong>Going back to starting HTML and CSS, was there something that made you want to start again and give it another try?</strong></p>
    <p>"Yeah, building a website is really fun and I was doing marketing and web development in my department. After I left that company I was in between thinking whether I should go the design route or go towards software development. I decided in the end to go with software development because I like learning and there's no way you can stop learning software. You have to be up-to-date with technology. It sounds so cliche but there’s so much that you need to keep learning because once you stop you are out of a job and you’re easily replaceable."</p>
    <p><strong>What would you recommend someone to take up or learn who’s beginning their route into development?</strong></p>
    <p>"I think you should Google 'How to become a software engineer' and it will come up with basic information and languages you should learn like HTML, CSS, and some basic language/ framework. But you need to feel and have a solid foundation in these three if you’re looking into front-end or web development. There’s so many resources out there."</p>
    <p><strong>Would you recommend a boot camp?</strong></p>
    <p>"I think some of the bootcamps here are overrated because they have so many students compared to instructor ratio. I think it should be 1-to-4 but some of them have one instructor to 12 or 16 students. There’s online resources: Treehouse, Udacity, Frontend Masters. Udacity and Treehouse are more project-based. I actually learned a lot from Udacity’s front-end nanodegree program. There were 5-6 projects that helped me get my current job.</p>
    <p>I think bootcamps are more of a social thing. Similar to why you go to college because there’s more structure and when you’re paying for something you feel you need to put in the effort. You go there to feel inspired and motivated and you know other people are going through the same experience."</p>
    <p><strong>What motivated you to go through the courses yourself? What were some obstacles?</strong></p>
    <p>"Not only software development, but when you’re in college or learning something new, everything requires just three or four personal characteristics - perseverance, greed, passion. You can do and learn anything in the long-term with these characteristics.</p>
    <p>I was working and I was studying (front-end) at the same time. It was a 9-5 job, just like anyone else, and afterwards I would put in six more hours of work - going through the material, reading a lot, and doing my projects.</p>
    <p>Of course, some days or most days, everything was so new and you’re building something on your own so I had to Google and try this and that to figure it out. I would ask friends or go to forums also. As a software engineer or developer you have to develop these frustrations and a tolerance for it. Because when you’re building stuff it’s not just that, you have to also fix a lot of bugs."</p>
    <p><strong>What advice would you give to someone who is trying to become a developer?</strong></p>
    <p>"First of all, don’t do it for the money. I think that’s the wrong path.</p>
    <p>My other advice to those who are learning is to know that you will fail and be rejected a hundred, 200, 500 times and there will be one or two companies that call you back for interviews on-site. And don’t get disappointed or upset that you’re not getting a job in your first 3 - 6 months, some people don't get a job until a year later. You have to be motivated to keep going; It’s more of a marathon than a sprint.</p>
    <p>Also, it doesn’t hurt to ask people when you’re learning as well. You have to remove your ego so that you can learn faster and better."</p>
    <p><strong>So you reach out to other friends for help?</strong></p>
    <p>"I reach out to a lot of people. I usually talk to random people and ask them what they do. When I was looking for jobs or studying for software development, I was reaching out to people on LinkedIn who were doing something similar like web development and front-end. I would ask them, 'Do you have 30 minutes?' or 'Could we grab some coffee sometime?'. Some of them would be nice enough to reply back and say, 'Let’s do it!'. And you start picking up different skills from them - how to interview and get better projects. There’s some people that don’t have much time and they’ll just be straightforward with you."</p>
    <p><strong>What was the best advice that you picked up?</strong></p>
    <p>"Not an advice, but just things anyone should be doing. Basically, learn your foundations really well because once you have these nailed down, you can branch out to different programming languages and frameworks quickly."</p>
    <p><strong>To reiterate, what are the foundations?</strong></p>
    <p>"For web development, HTML, CSS, and Javascript. Most companies are using javascript and its framework for front-end development, so once you know these three, it becomes easier for you learn frameworks like ReactJS, Angular, and others."</p>
    <p><strong>I’ve always found you to be a very optimistic person. You post really encouraging and positive entries on your LinkedIn. They’re really motivating. Do you have any final words branching off of those thoughts?</strong></p>
    <p>"I think being positive has helped me a lot in college, life, and my career. It’s shaped my thinking, mindset, and endurance to go through hardships. Let’s be real, everyone has faced rejection at some point, so when you receive rejection from a company or person you have to learn to deal with it and move on. If you stay there you will feel terrible. It’s a mental game: once you’re strong enough to deal with your own mind, then you can do anything you want to do or anything you want to become.</p>
    <p>Thanks for the great interview =)</p>
    <p>You can find me at <a href="https://www.instagram.com/rchrdchn/" target="_blank" rel="noopener noreferrer">Instagram</a> and <a href="https://medium.com/@rchrdchn" target="_blank" rel="noopener noreferrer">Medium</a> - both @rchrdchn"</p>
    <p><em>For more awesome stories check out our <a href="https://www.facebook.com/buzzybee.io/" target="_blank" rel="noopener noreferrer">facebook</a> and <a href="https://medium.com/@buzzybeeio268" target="_blank" rel="noopener noreferrer">medium</a> page!</em></p>
  </div>
);

export default Story;
